export const DEFAULT_FAVORITES = [
  'Messprotokolle',
  'Elektrische Messungen',
  'DIN-XP + HCO einstellen',
  'Klimamodul',
  'Tankwasserpumpe + Alarm',
  'Deckenlüfterkassetten testen',
  'Verplomben',
  'TK-Druckschalter testen',
  'P-Touch Pickerl (Position, Abtauzeit, Fühlerposition)',
  'Gaskühler HD-Leitung isolieren',
  'Sauggasfühler bei Kühlzelle isolieren',
  'Ausdehnungsgefäß auf 1,5 bar einstellen',
  'Rücktransport vorbereiten',
  '3M-Klebereste entfernen',
  'Pfeile + Pickerl (Rohre + Türe Kühlraum)',
  'Einschulung der Anlage',
  'Kühlzellenregler schließen (alle Regler)',
  'Servicepickerl beim Mängelbeheber',
  'Honeywell testen',
  'Umschaltventile testen',
  'Zonenventile testen',
  'Heizungsmodul einschalten',
  'Verkaufsfühler Mitte Geschäft',
  'Alarmweiterleitung testen',
  'IP-Adresse einstellen',
  'Wasserprobe durchführen',
  'Beschriften',
  'Zublenden + Zwischendecke',
  'Filter getauscht MO',
  'Fühler Deckenkassette montieren',
  'Pläne aufkleben',
  'Kabel beschriften',
  'Klima Backbox testen',
  'TWA Pumpe Getränke + Fleisch',
  'Kühlzellen Pickerl + GWA (Blitzleuchte)',
  'Adresse + Abtauzeit + TWP + GWA prüfen',
  'Anlagenbuch erstellen',
]

export const PROJECT_TEMPLATES: Record<string, string[]> = {
  'CO₂-Verbundanlage': [
    'Messprotokolle',
    'Elektrische Messungen',
    'DIN-XP + HCO einstellen',
    'Gaskühler HD-Leitung isolieren',
    'Sauggasfühler bei Kühlzelle isolieren',
    'Ausdehnungsgefäß auf 1,5 bar einstellen',
    'TK-Druckschalter testen',
    'Alarmweiterleitung testen',
    'IP-Adresse einstellen',
    'Anlagenbuch erstellen',
    'Verplomben',
    'Einschulung der Anlage',
    'P-Touch Pickerl (Position, Abtauzeit, Fühlerposition)',
    'Kühlzellenregler schließen (alle Regler)',
  ],
  'Split-Klimaanlage': [
    'Elektrische Messungen',
    'Klimamodul',
    'IP-Adresse einstellen',
    'Klima Backbox testen',
    'Alarmweiterleitung testen',
    'Beschriften',
    'Kabel beschriften',
    'Einschulung der Anlage',
    'Verplomben',
  ],
  'Wärmepumpe': [
    'Messprotokolle',
    'Elektrische Messungen',
    'Tankwasserpumpe + Alarm',
    'Heizungsmodul einschalten',
    'Ausdehnungsgefäß auf 1,5 bar einstellen',
    'Wasserprobe durchführen',
    'IP-Adresse einstellen',
    'Alarmweiterleitung testen',
    'Einschulung der Anlage',
    'Anlagenbuch erstellen',
  ],
  'Kühlzelle': [
    'Messprotokolle',
    'Elektrische Messungen',
    'Sauggasfühler bei Kühlzelle isolieren',
    'Pfeile + Pickerl (Rohre + Türe Kühlraum)',
    'Kühlzellenregler schließen (alle Regler)',
    'Kühlzellen Pickerl + GWA (Blitzleuchte)',
    'P-Touch Pickerl (Position, Abtauzeit, Fühlerposition)',
    'Adresse + Abtauzeit + TWP + GWA prüfen',
    'Verplomben',
    'Einschulung der Anlage',
  ],
  'Supermarkt': [
    'Messprotokolle',
    'Elektrische Messungen',
    'DIN-XP + HCO einstellen',
    'Klimamodul',
    'Tankwasserpumpe + Alarm',
    'Deckenlüfterkassetten testen',
    'Verplomben',
    'TK-Druckschalter testen',
    'P-Touch Pickerl (Position, Abtauzeit, Fühlerposition)',
    'Gaskühler HD-Leitung isolieren',
    'Sauggasfühler bei Kühlzelle isolieren',
    'Ausdehnungsgefäß auf 1,5 bar einstellen',
    'Honeywell testen',
    'Umschaltventile testen',
    'Zonenventile testen',
    'Heizungsmodul einschalten',
    'Verkaufsfühler Mitte Geschäft',
    'Alarmweiterleitung testen',
    'IP-Adresse einstellen',
    'TWA Pumpe Getränke + Fleisch',
    'Kühlzellen Pickerl + GWA (Blitzleuchte)',
    'Adresse + Abtauzeit + TWP + GWA prüfen',
    'Anlagenbuch erstellen',
    'Einschulung der Anlage',
    'Pläne aufkleben',
    'Zublenden + Zwischendecke',
    'Filter getauscht MO',
  ],
}
